### ISSUE TITLE
clocks are switching

### ISSUE THREAD

**Issue by CloudFluxx** [MK-AD/Pomodoro_py#1]
when one hits the **start-button** while the clock is running "_short break_" is showing and a corresponding 5 min clock is counting down the break-time

- this very clock is switching to the main clock and back in short-intervalls 
- moveover the main-clock is counting down too
- if one ends the break before the 5 mins are over the _clock-switching_ keeps on going

**Comment by MK-AD** [comment]
@CloudFluxx thanks for reporting the issue.
I fixed it with the last commit.
